### PR TITLE
Fixing broken build by replacing RGB with HDR

### PR DESCRIPTION
**Pull request by jodha**
Hi Erik - my first attempt at creating a pull request.

### CODE REVIEW

**Review by estrac — CHANGES_REQUESTED** [review]
Thanks for finding this! I took a look at the Dear ImGui Changelog (https://github.com/ocornut/imgui/blob/master/docs/CHANGELOG.txt) and they recommend changing to ImGuiColorEditFlags_DisplayRGB (it's interesting that the also deprecated "ImGuiColorEditFlags_HDR" worked).

Could you make this change?

Dear ImGui Changelog:
- Commented out redirecting functions/enums names that were marked obsolete in 1.69, 1.70, 1.71, 1.72 (March-July 2019)
  - ImGui::SetNextTreeNodeOpen()        -> use ImGui::SetNextItemOpen()
  - ImGui::GetContentRegionAvailWidth() -> use ImGui::GetContentRegionAvail().x
  - ImGui::TreeAdvanceToLabelPos()      -> use ImGui::SetCursorPosX(ImGui::GetCursorPosX() + ImGui::GetTreeNodeToLabelSpacing());
  - ImFontAtlas::CustomRect             -> use ImFontAtlasCustomRect
  - ImGuiColorEditFlags_RGB/HSV/HEX     -> use ImGuiColorEditFlags_DisplayRGB/HSV/Hex

**Comment by estrac** [comment]
I just downloaded the CMake gui from https://cmake.org/download/, blew away the build directory, used CMake gui to configure, I selected the tests and utilities option, configured again, generated and then rebuilt with the same error appearing in two of the tests.

**Comment by jodha** [comment]
Hey Erik - you are off and busy! I didn’t see any emails either, which is strange. I will have to check my junk folder. Currently I did update my cmake so I have the gui. I have to run to my tennis commitment, and I am having fun with this work!

**Comment by estrac** [comment]
Awesome! You can copy the imgui_demo.cpp from the sub modules directory.

I’m out in Old Town with my kids.

Erik

Sent from my iPhone

On Feb 5, 2022, at 11:23 AM, jodha ***@***.***> wrote:

﻿

Hey Erik - you are off and busy! I didn’t see any emails either, which is strange. I will have to check my junk folder. Currently I did update my cmake so I have the gui. I have to run to my tennis commitment, and I am having fun with this work!

Sent from my iPhone

> On Feb 5, 2022, at 10:15 AM, Erik Strack ***@***.***> wrote:
>
> ﻿
> I just downloaded the CMake gui from https://cmake.org/download/, blew away the build directory, used CMake gui to configure, I selected the tests and utilities option, configured again, generated and then rebuilt with the same error appearing in two of the tests.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Festrac%2FSimpleRenderEngine%2Fpull%2F1%23issuecomment-1030674521&data=04%7C01%7C%7Ce7bae7611de64e76c0b008d9e8d495d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637796822007178068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sZwha1rYBdowWIHnd9%2Buo9BkDmtOSL4sRt%2FXdyUHFdw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGJR5J642XQUQBI55SQGLWLUZVTJNANCNFSM5NTIOBXQ&data=04%7C01%7C%7Ce7bae7611de64e76c0b008d9e8d495d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637796822007178068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3vueAnmwf5%2BRoluCqGMax9MktppOyFRW%2FkctH4pL1bc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce7bae7611de64e76c0b008d9e8d495d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637796822007178068%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tM2us8gMnKyM7LkOKqU1FfxigS6P1f9WFQfClUHwQl4%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce7bae7611de64e76c0b008d9e8d495d4%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637796822007334304%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3ZYG6vFWVMt0zXaojsY7n%2F7MUBKnqznG0gI9NJpYPJY%3D&reserved=0>.

**Comment by jodha** [comment]
Hey Erik -

I don't think I know how pull requests work, but I did add another commit
to the change you mentioned before.  After I pushed it to my fork, it looks
like it automatically becomes a part of the previous pull request.

I didn't revert the other commit, because I didn't want my git fu to mess
up the repo.

-Manoj

**Comment by estrac** [comment]
Nice work - thanks again!

**Comment by estrac** [comment]
Hi Manoj,

I think that worked great - you second commit just overwrote the first commit. Yeah, I don’t know if a revert would have kept the pull request open…

BTW, when you made the pull request, GitHub notified me that I didn’t have any tests set up in GitHub Actions. So, if you have the energy and desire, you could try to enable the same tests for this repository (basically build tests) that used to get run on Travis CI. I think I saw a Travis.yml file somewhere, that is probably a good starting point…

Have fun! How does it feel to be out making waves on GitHub?

Erik


Sent from my iPhone

On Feb 5, 2022, at 5:54 PM, jodha ***@***.***> wrote:

﻿

Hey Erik -

I don't think I know how pull requests work, but I did add another commit
to the change you mentioned before. After I pushed it to my fork, it looks
like it automatically becomes a part of the previous pull request.

I didn't revert the other commit, because I didn't want my git fu to mess
up the repo.

-Manoj

**Pull request merged**
